import { Noto_Sans_KR } from "next/font/google";
import type { Metadata } from "next";
import "@/styles/index.css";
import Header from "@/components/layout/header";
import OrbitingElements from "@/components/ui/orbiting-elements";
import AnimatedBackgroundElements from "@/components/ui/animated-background-elements";
import Footer from "@/components/layout/footer";
import EthereumProvider from "@/components/ethereum-provider";
import QueryProvider from "@/components/query-provider";
import { cookieToInitialState } from "wagmi";
import { getConfig } from "@/configs/wagmi-config";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: {
    template: "%s | PLUMERIA",
    default: "PLUMERIA",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const notoSansKR = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  preload: true,
  display: "swap",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(
    getConfig(),
    (await headers()).get("cookie")
  );

  return (
    <html lang="ko" className={notoSansKR.className}>
      <body className="relative w-full">
        <EthereumProvider initialState={initialState}>
          <QueryProvider>
            <Header />
            <main className="min-h-screen">{children}</main>
            <Footer />
          </QueryProvider>
        </EthereumProvider>

        {/* Background */}
        <div className="fixed inset-0 pointer-events-none h-screen overflow-hidden">
          <OrbitingElements />
          <AnimatedBackgroundElements />
        </div>
      </body>
    </html>
  );
}
